version: '3.9' 

services:
  db:
    image: postgres:15.0 
    command: 
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    volumes:
      - type: volume
        source: postgresdb-data-lab3
        target: /var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: car_user
      POSTGRES_DB: car_devices
      POSTGRES_PASSWORD: car_password
      PGDATA: "/var/lib/postgresql/data/pgdata" 
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U car_user -d car_devices"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped 
    deploy: 
      resources:
        limits:
          cpus: '3'
          memory: 4G
    networks:
      - car-network-lab3

  minio:
    container_name: minio_car_lab3
    image: minio/minio:latest
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ACCESS_KEY: car_user
      MINIO_SECRET_KEY: car_password
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data-lab3:/data
    command: server /data
    networks:
      - car-network-lab3

  redis:
    image: redis:6.2-alpine
    container_name: redis_car_lab3
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass "" --protected-mode no
    volumes:
      - redis-data-lab3:/data
    networks:
      - car-network-lab3

  adminer:
    image: adminer:latest 
    container_name: adminer_car_lab3
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres_car_lab3
    depends_on:
      - db
    networks:
      - car-network-lab3

volumes:
  postgresdb-data-lab3:
    driver: local
  minio-data-lab3:
    driver: local
  redis-data-lab3:
    driver: local

networks:
  car-network-lab3:
    driver: bridge